spring:
    application:
        name: taco
    output:
        ansi:
            enabled: ALWAYS
    datasource:
        generate-unique-name: false
        name: taco
        # username: ianco
        # password: tacopass
    security:
        user:
            name: ianco
            password: tacopass
server:
    port: 8443
    servlet:
        context-path: /taco
    ssl:
        key-store: classpath:keystore/tacokeys.jks
        key-store-password: tacopass
        key-password: tacopass

taco:
    orders:
        pageSize: 20