spring:
    application:
        name: taco
    output:
        ansi:
            enabled: ALWAYS
    datasource:
        generate-unique-name: false
        name: tacodb
    security:
        user:
            name: ianco
            password: tacopass
    h2:
        console:
            enabled: true
            path: /h2-console
server:
    port: 8443
    servlet:
        context-path: /taco
    ssl:
        key-store: classpath:keystore/tacokeys.jks
        key-store-password: tacopass
        key-password: tacopass
taco:
    props:
        pageSize: 20
    # model-props:
    #     min-str-len: 5
    #     max-str-len: 100
    #     min-username-len: 3
    #     max-username-len: 12
    #     min-password-len: 3
    #     max-password-len: 15
    #     state-len: 2
    #     zip-len: 8
    #     phone-len: 11
---
spring:
    config:
        activate.on-profile: test
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:h2:file:./.db/tacodb
        username: tacouser
        password: tacoh2pass
        driver-class-name: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
---
spring:
    config:
        activate.on-profile: prod
    datasource:
        url: jdbc:mysql://localhost:3306/tacodb
        username: tacodbuser
        password: tacodbpass