spring:
    application:
        name: taco
    output:
        ansi:
            enabled: ALWAYS
    datasource:
        generate-unique-name: false
        name: taco
        # url: jdbc:h2:taco
        # url: jdbc:mysql://localhost/tacodb
        # username: ianco
        # password: tacopass


server:
    port: 8443
    servlet:
        context-path: /taco
    ssl:
        key-store: classpath:keystore/tacokeys.jks
        key-store-password: tacopass
        key-password: tacopass