spring:
    application:
        name: taco
    output:
        ansi:
            enabled: ALWAYS
    datasource:
        generate-unique-name: false
        name: taco
    security:
        user:
            name: ianco
            password: tacopass
server:
    port: 8443
    servlet:
        context-path: /taco
    ssl:
        key-store: classpath:keystore/tacokeys.jks
        key-store-password: tacopass
        key-password: tacopass

taco:
    orders:
        pageSize: 20
---
spring:
    config:
        activate.on-profile: prod
    datasource:
        url: jdbc:mysql://localhost:3306/tacodb
        username: tacodbuser
        password: tacodbpass